language: node_js
node_js:
  - "10"
  - '15.0.0'
env:
  global:
    - NPM_EMAIL=$EMAIL
    - NPM_TOKEN=$NPM_TOKEN

install:
  - npm i

script:
  - echo "npm run building ----"
  - npm run build

branch:
  - master
    deploy:
      provider: npm
      email: "$NPM_EMAIL"
      api_key: "$NPM_TOKEN"
      skip_cleanup: true
      on:
        branch: master
